### PR TITLE
Update locks Ids and relations

### PR DESCRIPTION
**Pull request by jodator**
Hi, I've started working on checking the conflicting locks in the Pioneer 2 and figured out that I might update the docs.

I wasn't sure whether the Bounty Lock is Binding (I'd guess that it is) so please fill that :)

### CODE REVIEW

**Comment by bedeho** [comment]
I think I have forgotten, what do you think @shamil-gadelshin ? please make sure to update handbook with correct conclusion :)

**Comment by shamil-gadelshin** [comment]
Yes. Bounty Lock is Binding.

**Comment by shamil-gadelshin** [comment]
It looks like my tiny (with Yes) PR will only create merge conflicts. @jodator Do you mind adding this `Yes` into your `patch-1`?

**Comment by jodator** [comment]
@shamil-gadelshin done :white\_check\_mark:

**Pull request closed without merging**
